name: Stratum
version: ${project.version}
main: tech.quilldev.Stratum
api-version: 1.16

commands:
  show:
    aliases:
      - present
      - linkitem
    usage: /<command> [slot (1-9)]
    description: links the item at the given slot in the chat
